export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
