export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST= "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET= "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
